config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  resources :questions
  resources :categories
  resources :attachments, only: %i[destroy]

  resources :quiz_sessions, only: %i[index] do
    scope module: 'quiz_sessions' do
      resources :questions, only: %i[index]
      resources :players, only: %i[index]
    end
  end

  scope module: 'host' do
    resources :quiz_sessions, only: %i[new create show] do
      member do
        put 'start', to: 'quiz_sessions#start'
        put 'next', to: 'quiz_sessions#next'
        put 'mark_answer', to: 'quiz_sessions#mark_answer'
        put 'deactivate_player', to: 'quiz_sessions#deactivate_player'
        put 'activate_player', to: 'quiz_sessions#activate_player'
        put 'rating', to: 'quiz_sessions#rating'
      end
    end
  end

  scope module: 'player' do
    get 'quiz_sessions/:id/play', to: 'quiz_sessions#show'
    post 'quiz_sessions/:id/answer', to: 'quiz_sessions#answer'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :sessions_questions, class_name: 'SessionsQuestion', dependent: :destroy
  has_many :quiz_sessions, through: :sessions_questions
  has_one_attached :image

  def not_used?
    quiz_sessions.blank?
  end

  scope :not_used, -> {
    left_joins(:quiz_sessions)
      .group('questions.id')
      .having('COUNT(quiz_sessions.id) = 0')
  }

  scope :general, -> {
    where(user_id: nil)
  }

  def session_answers(quiz_session)
    quiz_session.quiz_answers.where(question: self)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = !!params[:general] ? Question.general : current_user.questions
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(user: current_user, **question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_path, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_path, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:text, :answer, :category_id, :image)
    end
end

app/controllers/quiz_sessions/questions_controller.rb
class QuizSessions::QuestionsController < ApplicationController
  before_action :find_quiz_session!

  def index
    @questions = @quiz_session.questions
  end

  private

  def find_quiz_session!
    @quiz_session = QuizSession.find(params[:quiz_session_id])
  end
end

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs" data-controller="image">
    <%= f.association :category, collection: current_user.categories.order(:name), include_blank: 'Choose category' %>
    <%= f.input :text %>
    <%= f.input :image, as: :file, input_html: { data: { action: 'image#showImage', image_target: 'imageInput' } } %>
    <div class="d-flex align-items-center" id="previewDiv">
      <img src="<%= url_for(@question.image) if @question.image.attached? %>" id="imagePreview" data-image-target="imagePreview" alt="Attached image"  />
      <% if @question.image.attached? %>
        <%= link_to '', attachment_path(@question.image.id), type: "button", class: "btn-close", data: { turbo_confirm: 'Are you sure?', turbo_method: :delete, action: "image#deleteImage" }, id: 'deleteImageBtn' %>
      <% end %>
    </div>
    <%= f.input :answer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<td>
  <%= question.id %>
</td>
<td>
  <%= question.text %>
</td>
<td>
  <%= question.answer %>
</td>
<td>
  <%= question.category.name %>
</td>
<td>
  <div class="d-flex">
    <%= link_to "Edit", edit_question_path(question), class: "btn btn-primary me-1" %>
    <%= button_to "Destroy", question, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</td>

app/views/questions/edit.html.erb
<div style="width: 100vw">
  <p class="text-center" style="color: green"><%= notice %></p>

  <h1 class="text-center">Edit question</h1>
  <div class="w-75 mx-auto">
    <%= render "form", question: @question %>
  </div>
</div>

app/views/questions/index.html.erb
<div style="width: 100vw">
  <p class="text-center" style="color: green"><%= notice %></p>

  <h1 class="text-center">Questions</h1>

  <div id="questions" class="d-flex flex-column align-items-center">
    <div style="width: 75%">
      <table class="table table-striped align-middle">
        <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Text</th>
          <th scope="col">Answer</th>
          <th scope="col">Category</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @questions.each do |question| %>
          <tr>
            <%= render question %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="w-75">
      <%= link_to "New question", new_question_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div style="width: 100vw">
  <p class="text-center" style="color: green"><%= notice %></p>

  <h1 class="text-center">New question</h1>
  <div class="w-75 mx-auto">
    <%= render "form", question: @question %>
  </div>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>