config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  resources :questions
  resources :categories
  resources :attachments, only: %i[destroy]

  resources :quiz_sessions, only: %i[index] do
    scope module: 'quiz_sessions' do
      resources :questions, only: %i[index]
      resources :players, only: %i[index]
    end
  end

  scope module: 'host' do
    resources :quiz_sessions, only: %i[new create show] do
      member do
        put 'start', to: 'quiz_sessions#start'
        put 'next', to: 'quiz_sessions#next'
        put 'mark_answer', to: 'quiz_sessions#mark_answer'
        put 'deactivate_player', to: 'quiz_sessions#deactivate_player'
        put 'activate_player', to: 'quiz_sessions#activate_player'
        put 'rating', to: 'quiz_sessions#rating'
      end
    end
  end

  scope module: 'player' do
    get 'quiz_sessions/:id/play', to: 'quiz_sessions#show'
    post 'quiz_sessions/:id/answer', to: 'quiz_sessions#answer'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
end

app/models/quiz_session.rb
class QuizSession < ApplicationRecord
  belongs_to :user
  has_many :sessions_questions, class_name: 'SessionsQuestion', dependent: :destroy
  has_many :questions, through: :sessions_questions
  has_many :sessions_players, class_name: 'SessionsPlayer', dependent: :destroy
  has_many :players, through: :sessions_players, source: :user
  has_many :quiz_answers

  enum status: {
    pending: 'pending',
    in_progress: 'in_progress',
    finished: 'finished'
  }

  enum session_type: {
    default: 'default',
    synchronous: 'synchronous'
  }

  def host
    @host ||= user
  end

  def current_question
    questions[current_question_index]
  end

  def current_answers
    quiz_answers.where(question: current_question).order(:created_at)
  end

  scope :related_to_user, ->(user) {
    includes(:sessions_players)
      .where(user_id: user.id)
      .or(QuizSession.where(sessions_players: { user_id: user.id }))
  }
end

app/controllers/host/quiz_sessions_controller.rb
class Host::QuizSessionsController < ApplicationController
  before_action :validate_user!, except: %i[new create]
  layout 'synchronous_quiz', except: %i[new]

  def new
    @quiz_session = QuizSession.new(name: "Session ##{current_user.quiz_sessions.count.next}")
  end

  def create
    result = QuizSessions::Create.call(user: current_user, **quiz_session_params)

    if result.success?
      redirect_to result.quiz_session
    else
      flash[:error] = result.errors
      redirect_to new_quiz_session_path, status: :unprocessable_entity
    end
  end

  def show
    if quiz_session.default?
      render 'host/quiz_sessions/default/show', layout: 'application'
    elsif quiz_session.synchronous?
      render_proper_page
    end
  end

  def start
    # TODO: move to service
    # TODO: change to render_later
    quiz_session.update!(status: :in_progress)

    quiz_session.broadcast_replace_to [quiz_session, current_user], target: 'host-quiz', template: 'host/quiz_sessions/synchronous/in_progress_session', locals: { quiz_session: quiz_session }
    quiz_session.broadcast_replace_to quiz_session, target: 'player-quiz', template: 'player/quiz_sessions/in_progress_session', locals: { quiz_session: quiz_session, answer: QuizAnswer.new }
  end

  def mark_answer
    answer = QuizAnswer.find(params[:quiz_answer][:id])

    if answer
      answer.update!(correct: params[:quiz_answer][:correct])
      quiz_session.broadcast_replace_to [quiz_session, current_user], target: helpers.dom_id(answer, :answer), partial: 'host/quiz_sessions/synchronous/mark_answer_form', locals: { answer: }
    end
  end

  def next
    quiz_session.increment!(:current_question_index)

    quiz_session.broadcast_replace_to [quiz_session, current_user], target: 'host-quiz', template: 'host/quiz_sessions/synchronous/in_progress_session', locals: { quiz_session: quiz_session }
    quiz_session.broadcast_replace_to quiz_session, target: 'player-quiz', template: 'player/quiz_sessions/in_progress_session', locals: { quiz_session: quiz_session, answer: QuizAnswer.new }
  end

  def rating
    if quiz_session.current_question_index + 1 == quiz_session.questions_count
      quiz_session.finished!
    end

    quiz_session.broadcast_replace_to [quiz_session, current_user], target: 'host-quiz', template: 'host/quiz_sessions/synchronous/session_rating', locals: { quiz_session: quiz_session }
    quiz_session.broadcast_replace_to quiz_session, target: 'player-quiz', template: 'player/quiz_sessions/session_rating', locals: { quiz_session: quiz_session }
    head :ok
  end

  def deactivate_player
    sessions_player = SessionsPlayer.find(params[:sessions_player][:id])

    if sessions_player
      sessions_player.update!(active: false)
    end

    quiz_session.broadcast_replace_to [quiz_session, current_user], target: helpers.dom_id(sessions_player, :player), partial: 'host/quiz_sessions/synchronous/activate_player_form', locals: { sessions_player: sessions_player }
    # TODO: replace and rename to 'player/excluded_page'
    quiz_session.broadcast_replace_to [quiz_session, sessions_player.user], target: 'player-quiz', template: 'host/quiz_sessions/synchronous/eliminated_page'
  end

  def activate_player
    sessions_player = SessionsPlayer.find(params[:sessions_player][:id])

    if sessions_player
      sessions_player.update!(active: true)
    end

    quiz_session.broadcast_replace_to [quiz_session, current_user], target: helpers.dom_id(sessions_player, :player), partial: 'host/quiz_sessions/synchronous/deactivate_player_form', locals: { sessions_player: sessions_player }
  end

  private

  def validate_user!
    if quiz_session.user != current_user
      redirect_to root_path, notice: 'You are not a host!'
    end
  end

  def render_proper_page
    if quiz_session.pending?
      # TODO: refactor it (maybe use has_one :svg or just replace it to method)
      quiz_play_url = url_for(quiz_session) + '/play'
      qrcode = RQRCode::QRCode.new(quiz_play_url)
      svg = qrcode.as_svg(color: "000", shape_rendering: "crispEdges", module_size: 5, standalone: true, use_path: true)
      render 'host/quiz_sessions/synchronous/pending_session', locals: { quiz_session: quiz_session, quiz_play_url: quiz_play_url, svg: svg }
    elsif quiz_session.in_progress?
      render 'host/quiz_sessions/synchronous/in_progress_session', locals: { quiz_session: quiz_session }
    elsif quiz_session.finished?
      render 'host/quiz_sessions/synchronous/session_rating', locals: { quiz_session: quiz_session }
    end
  end

  def quiz_session
    @quiz_session ||= QuizSession.find(params[:id])
  end

  def quiz_session_params
    params.require(:quiz_session).permit(:name, :questions_count, :only_free, :session_type, category_ids: [])
  end
end

app/controllers/player/quiz_sessions_controller.rb
class Player::QuizSessionsController < ApplicationController
  before_action :validate_quiz_session!
  before_action :validate_player!
  layout 'synchronous_quiz'

  def show
    result = QuizSessions::Synchronous::ProcessPlayers.call(
      quiz_session: quiz_session,
      current_user: current_user
    )

    if result.failure?
      redirect_to root_path, notice: result.errors
    else
      render_proper_page
    end
  end

  def answer
    # TODO: move to service
    answer = quiz_session.quiz_answers.build(
      user: current_user,
      question: question,
      text: params[:quiz_answer][:text]
    )

    if answer.save
      quiz_session.broadcast_append_to quiz_session,
                                       target: 'answers-list',
                                       partial: 'host/quiz_sessions/synchronous/answer',
                                       locals: { answer: answer }

      quiz_session.broadcast_replace_to [quiz_session, current_user], target: "player-quiz", template: 'player/quiz_sessions/waiting', locals: { quiz_session: quiz_session, question: }
    else
      render turbo_stream: turbo_stream.replace('answer_form', partial: 'player/quiz_sessions/answer', locals: { answer: answer, quiz_session: quiz_session })
    end
  end

  private

  def render_proper_page
    if quiz_session.pending?
      render 'player/quiz_sessions/pending_session', locals: { quiz_session: quiz_session }
    elsif quiz_session.in_progress?
      if quiz_session.quiz_answers.where(user: current_user, question: question).any?
        render 'player/quiz_sessions/waiting', locals: { quiz_session: quiz_session, question: }
      else
        render 'player/quiz_sessions/in_progress_session', locals: { quiz_session: quiz_session, answer: QuizAnswer.new }
      end
    elsif quiz_session.finished?
      render 'player/quiz_sessions/session_rating', locals: { quiz_session: quiz_session }
    end
  end

  def quiz_session
    @quiz_session ||= QuizSession.find(params[:id])
  end

  def question
    @question ||= quiz_session.current_question
  end

  def validate_quiz_session!
    if quiz_session.default?
      redirect_to root_path, notice: 'For requested quiz url was forbidden'
    elsif quiz_session.user == current_user
      redirect_to quiz_session, notice: 'You are the host of this quiz!'
    end
  end

  def validate_player!
    if quiz_session.sessions_players.where(user: current_user, active: false).any?
      redirect_to root_path, notice: 'You were excluded from that quiz.'
    end
  end
end

app/controllers/quiz_sessions/players_controller.rb
class QuizSessions::PlayersController < ApplicationController
  before_action :find_quiz_session!

  def index
    @players = @quiz_session.sessions_players
                            .sort_by { |player| player.points }
                            .reverse
  end

  private

  def find_quiz_session!
    @quiz_session = QuizSession.find(params[:quiz_session_id])
  end
end

app/controllers/quiz_sessions/questions_controller.rb
class QuizSessions::QuestionsController < ApplicationController
  before_action :find_quiz_session!

  def index
    @questions = @quiz_session.questions
  end

  private

  def find_quiz_session!
    @quiz_session = QuizSession.find(params[:quiz_session_id])
  end
end

app/controllers/quiz_sessions_controller.rb
class QuizSessionsController < ApplicationController
  def index
    @quiz_sessions = QuizSession.related_to_user(current_user)
  end
end

app/views/host/quiz_sessions/synchronous/_activate_player_form.html.erb
<%= turbo_frame_tag dom_id(sessions_player, :player) do %>
  <%= form_with model: sessions_player, url: activate_player_quiz_session_path(sessions_player.quiz_session), method: :put do |f| %>
    <%= f.hidden_field :id %>
    <%= f.submit 'Activate player', class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/host/quiz_sessions/synchronous/_answer.html.erb
<tr>
  <td>
    <%= player_avatar(answer.user) %>
    <%= answer.user.nickname %>
  </td>
  <td><%= answer.text %></td>
  <td>
    <%= render 'host/quiz_sessions/synchronous/mark_answer_form', answer: answer %>
  </td>
</tr>

app/views/host/quiz_sessions/synchronous/_answers.html.erb
<h2>Wait for answers:</h2>
<table class="table table-striped align-middle">
  <thead>
  <tr>
    <th scope="col">Nickname</th>
    <th scope="col">Answer</th>
    <th scope="col">Correct?</th>
  </tr>
  </thead>
  <tbody id="answers-list">
  <%= render partial: 'host/quiz_sessions/synchronous/answer', collection: quiz_answers, as: :answer %>
  </tbody>
</table>

app/views/host/quiz_sessions/synchronous/_deactivate_player_form.html.erb
<%= turbo_frame_tag dom_id(sessions_player, :player) do %>
  <%= form_with model: sessions_player, url: deactivate_player_quiz_session_path(sessions_player.quiz_session), method: :put do |f| %>
    <%= f.hidden_field :id %>
    <%= f.submit 'Deactivate player', data: { turbo_confirm: 'Are you sure you want to deactivate this user from this quiz?' }, class: 'btn btn-danger' %>
  <% end %>
<% end %>

app/views/host/quiz_sessions/synchronous/_mark_answer_form.html.erb
<%= turbo_frame_tag dom_id(answer, :answer) do %>
  <%= form_with model: answer, url: mark_answer_quiz_session_path(answer.quiz_session), method: :put, class: 'd-flex justify-content-around w-50' do |f| %>
    <%= f.hidden_field :id %>
    <div class="d-flex align-items-center justify-content-between">
      <div class="form-check me-2">
        <%= f.radio_button :correct, false, class: 'form-check-input' %>
        <%= f.label :correct, "No", value: "false", class: 'form-check-label', for: "quiz_answer_correct_false" %>
      </div>
      <div class="form-check me-2">
        <%= f.radio_button :correct, true, class: 'form-check-input' %>
        <%= f.label :correct, "Yes", value: "true", class: 'form-check-label', for: "quiz_answer_correct_true"  %>
      </div>
      <% if answer.correct == nil %>
        <%= f.submit 'Save', data: { action: 'answers#save' }, class: 'btn btn-success' %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/host/quiz_sessions/synchronous/_player.html.erb
<tr>
  <td>
    <%= player_avatar(sessions_player.user) %>
    <%= sessions_player.user.nickname %>
  </td>
  <td>
    <%= turbo_frame_tag dom_id(sessions_player, :player) do %>
      <% if sessions_player.active? %>
        <%= render 'host/quiz_sessions/synchronous/deactivate_player_form', sessions_player: sessions_player %>
      <% else %>
        <%= render 'host/quiz_sessions/synchronous/activate_player_form', sessions_player: sessions_player %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/host/quiz_sessions/synchronous/_players.html.erb
<table class="table table-striped align-middle">
  <thead>
  <tr>
    <th scope="col">Nickname</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody id="players-host-list" class="table-striped">
    <%= render partial: 'host/quiz_sessions/synchronous/player', collection: quiz_session.sessions_players, as: :sessions_player %>
  </tbody>
</table>

app/views/host/quiz_sessions/synchronous/_rating.html.erb
<table class="table table-striped align-middle" id="ratingTable" data-controller="rating">
  <thead>
  <tr>
    <th scope="col">Nickname</th>
    <th scope="col">Points</th>
  </tr>
  </thead>
  <tbody>

  <% quiz_session.players.each do |player| %>
    <tr>
      <td>
        <%= player_avatar(player) %>
        <%= player.nickname %>
      </td>
      <td><%= player.points_count(quiz_session) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/host/quiz_sessions/synchronous/eliminated_page.html.erb
<h1>You have been eliminated from the quiz :(</h1>

app/views/host/quiz_sessions/synchronous/in_progress_session.html.erb
<%= turbo_frame_tag 'host-quiz' do %>
  <div class="d-flex justify-content-center align-items-center vw-100 h-100 my-5">
    <div>
      <div data-controller="answers">
        <%= render 'host/quiz_sessions/default/question', question: quiz_session.current_question, answer: 'visible' %>
        <br>
          <%= render 'host/quiz_sessions/synchronous/answers', quiz_answers: quiz_session.current_answers %>
        <br>

        <%= link_to 'Show rating', rating_quiz_session_path(quiz_session),
                    data: {
                      turbo_method: :put,
                      answers_target: 'ratingBtn',
                      turbo_confirm: 'Are you sure? Maybe not all players responded!'
                    },
                    class: 'btn btn-primary'
        %>
      </div>
    </div>
  </div>
<% end %>

app/views/host/quiz_sessions/synchronous/pending_session.html.erb
<%= turbo_frame_tag 'host-quiz' do %>
  <div class="d-flex justify-content-center align-items-center vw-100 h-100 my-5">
    <div>
      <p class="text-center" style="color: green"><%= notice %></p>

      <h2>Connected players:</h2>

      <%= render 'host/quiz_sessions/synchronous/players', quiz_session: quiz_session %>

      <div class="d-flex flex-column align-items-center justify-content-center">
        <h2>Use this for sharing quiz url:</h2>
        <%= svg.html_safe %>
        <h3>or</h3>
        <div data-controller="clipboard" data-clipboard-success-content-value="Copied!" class="d-flex flex-column align-items-center">
          <p data-clipboard-target="source"><%= quiz_play_url %></p>
          <button type="button" data-action="clipboard#copy" data-clipboard-target="button" class="btn btn-warning">Copy to clipboard</button>
        </div>
        <%= link_to 'Start!', start_quiz_session_path, data: { turbo_method: :put }, class: 'btn btn-success mt-3' %>
      </div>
    </div>
  </div>
<% end %>

app/views/host/quiz_sessions/synchronous/session_rating.html.erb
<%= turbo_frame_tag 'host-quiz' do %>
  <div class="d-flex justify-content-center align-items-center vw-100 h-100 my-5">
    <div>
      <%= render 'host/quiz_sessions/synchronous/rating', quiz_session: quiz_session %>

      <% if quiz_session.in_progress? %>
        <%= link_to 'Next!', next_quiz_session_path(quiz_session), data: { turbo_method: :put }, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to 'Home!', root_path, data: { turbo: false }, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
<% end %>