config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  resources :questions
  resources :categories
  resources :attachments, only: %i[destroy]

  resources :quiz_sessions, only: %i[index] do
    scope module: 'quiz_sessions' do
      resources :questions, only: %i[index]
      resources :players, only: %i[index]
    end
  end

  scope module: 'host' do
    resources :quiz_sessions, only: %i[new create show] do
      member do
        put 'start', to: 'quiz_sessions#start'
        put 'next', to: 'quiz_sessions#next'
        put 'mark_answer', to: 'quiz_sessions#mark_answer'
        put 'deactivate_player', to: 'quiz_sessions#deactivate_player'
        put 'activate_player', to: 'quiz_sessions#activate_player'
        put 'rating', to: 'quiz_sessions#rating'
      end
    end
  end

  scope module: 'player' do
    get 'quiz_sessions/:id/play', to: 'quiz_sessions#show'
    post 'quiz_sessions/:id/answer', to: 'quiz_sessions#answer'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :destroy

  scope :general, -> {
    where(user_id: nil)
  }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = !!params[:general] ? Category.general : current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(user: current_user, **category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_category.html.erb
<td>
  <%= category.id %>
</td>
<td>
  <%= category.name %>
</td>
<td>
  <div class="d-flex justify-content-center">
    <%= link_to "Edit", edit_category_path(category), class: "btn btn-primary me-1" %>
    <%= button_to "Destroy", category, method: :delete, data: { turbo_confirm: 'Are you sure? All related questions will remove!' }, class: "btn btn-danger" %>
  </div>
</td>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div style="width: 100vw">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center">Edit category</h1>
  <div class="w-75 mx-auto">
    <%= render "form", category: @category %>
  </div>
</div>

app/views/categories/index.html.erb
<div style="width: 100vw">
  <p class="text-center" style="color: green"><%= notice %></p>

  <h1 class="text-center">Categories</h1>

  <div id="categories" class="d-flex flex-column align-items-center">
    <div style="width: 75%">
      <table class="table table-striped align-middle">
        <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
          <tr>
            <%= render category %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="w-75">
      <%= link_to "New category", new_category_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div style="width: 100vw">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center">New category</h1>
  <div class="w-75 mx-auto">
    <%= render "form", category: @category %>
  </div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>